//
// Generated file, do not edit! Created by nedtool 4.6 from dpdu.msg.
//

#ifndef _DPDU_M_H_
#define _DPDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>dpdu.msg:20</tt> by nedtool.
 * <pre>
 * packet Dpdu
 * {
 *     int id;
 *     int src;
 *     int dest;
 *     bool type;
 * }
 * </pre>
 */
class Dpdu : public ::cPacket
{
  protected:
    int id_var;
    int src_var;
    int dest_var;
    bool type_var;

  private:
    void copy(const Dpdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Dpdu&);

  public:
    Dpdu(const char *name=NULL, int kind=0);
    Dpdu(const Dpdu& other);
    virtual ~Dpdu();
    Dpdu& operator=(const Dpdu& other);
    virtual Dpdu *dup() const {return new Dpdu(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual bool getType() const;
    virtual void setType(bool type);
};

inline void doPacking(cCommBuffer *b, Dpdu& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Dpdu& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DPDU_M_H_

