//
// Generated file, do not edit! Created by nedtool 4.6 from ppdu.msg.
//

#ifndef _PPDU_M_H_
#define _PPDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ppdu.msg:20</tt> by nedtool.
 * <pre>
 * packet Ppdu
 * {
 *     int src;
 *     int dest;
 *     bool type;
 * }
 * </pre>
 */
class Ppdu : public ::cPacket
{
  protected:
    int src_var;
    int dest_var;
    bool type_var;

  private:
    void copy(const Ppdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ppdu&);

  public:
    Ppdu(const char *name=NULL, int kind=0);
    Ppdu(const Ppdu& other);
    virtual ~Ppdu();
    Ppdu& operator=(const Ppdu& other);
    virtual Ppdu *dup() const {return new Ppdu(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual bool getType() const;
    virtual void setType(bool type);
};

inline void doPacking(cCommBuffer *b, Ppdu& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Ppdu& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PPDU_M_H_

